services:

  ninjalynx:
    build: .
    ports: 
      - 3000:3000
    environment:
      - PROD_MONGODB_DATABASE=mongodb://mongo:27017/ninjalynx
    depends_on:
      - mongo  

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:

  # mongo:
  #   image: mongo
  #   ports:
  #     - 0.0.0.0:27017:27017
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example